/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleView: typeof import('./src/pages/ArticleView.vue')['default']
    CommunityView: typeof import('./src/pages/CommunityView.vue')['default']
    DiscoverView: typeof import('./src/pages/DiscoverView.vue')['default']
    HomeView: typeof import('./src/pages/HomeView.vue')['default']
    HotTopic: typeof import('./src/components/HotTopic.vue')['default']
    IconTablerSearch: typeof import('~icons/tabler/search')['default']
    MessageView: typeof import('./src/pages/MessageView.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PrivacyPolicyView: typeof import('./src/pages/PrivacyPolicyView.vue')['default']
    ProfileView: typeof import('./src/pages/ProfileView.vue')['default']
    QuickActionCard: typeof import('./src/components/QuickActionCard.vue')['default']
    RecommendCard: typeof import('./src/components/RecommendCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingView: typeof import('./src/pages/SettingView.vue')['default']
    SigninView: typeof import('./src/pages/SigninView.vue')['default']
    SignupView: typeof import('./src/pages/SignupView.vue')['default']
    StatisticsCard: typeof import('./src/components/StatisticsCard.vue')['default']
    TopicCard: typeof import('./src/components/TopicCard.vue')['default']
    UserAgreementView: typeof import('./src/pages/UserAgreementView.vue')['default']
    UserInfoCard: typeof import('./src/components/UserInfoCard.vue')['default']
  }
}
